spring.application.name=boot_react
debug=true
# 기본포트 : 8080
# server.port=8080
# mariaDB 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/springbootdb
spring.datasource.username=user
spring.datasource.password=4986
# Connection Pool 설정
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.read-only=false
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.maximum-pool-size=20
#JPA 관련 설정
#엔티티클래스에 맞도록 db의 테이블을 변경하기. (개발환경)
spring.jpa.hibernate.ddl-auto=update
#실제 실행되는 SQL 구문을 콘솔에 출력 (개발환경)
spring.jpa.show-sql=true
# 파일 업로드
spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB
board.upload.dir=C:/Dev/spring-boot/boot-react/src/main/resources/static/